### ISSUE TITLE
Host must have an interface declared

### ISSUE THREAD

**Issue by rkhadro** [cskollar/zabbix-oneview#1]
Hi Cskollar,

I'm testing your template.
In order to have it work, i have to config an bogus interface on the Host created.
if not Enclosure and Blade are correctly discovered but not filled.
When you show the items for the host,  caution sign is displayed (info column) for the 3 Get (not Get Alerts) 
The warning message says that the host doesn't have an interface.

After populated the host interface, all is working.

 I'm interested in virtual connect metrics, if you want some testing.

**Comment by cskollar** [comment]
Sorry for the delayed response...

The LLDs within the template utilize the 'Host prototype' item to create hosts. The current configuration is such that the hosts created by the LLDs inherit the settings of the main host (OneView) interface. As a result, all server blade, enclosure and logical enclosure interfaces will have the same IP address and type of the interface (Agent) as the base host (the OneView).

So if you create an agent interface on the main host (OneView), the hosts created by LLDs will be good. This isn't ideal, but it's inconsequential since these interfaces isn't used anywhere in the template.
